# Generated by Django 3.1.7 on 2022-06-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
    ]
